/*
 Generate Valid Angle Bracket Sequences
 Given n, return all valid sequences of n pairs of '<' and '>' with proper nesting.

 Examples
 Example 1

 Input:

 n = 1
 Output:

 <>
 Explanation:

 With one pair of angle brackets, the only valid nesting is "< >".
 The function starts with an empty string and can only place a '<' then a '>' yielding "<>".
 Example 2

 Input:

 n = 2
 Output:

 <><>
 <<>>
 Explanation:

 There are two valid sequences for two pairs:
 "<><>" — place the two pairs side by side.
 "<<>>" — nest the second pair inside the first.
 The backtracking builds these by adding '<' when we have not yet placed 2, and '>' when there is an unmatched '<'.
 Example 3

 Input:

 n = 3
 Output:

 <<<>>>
 <<><>>
 <<>><>
 <><<>>
 <><><>
 Explanation:

 For three pairs, there are 5 valid sequences (analogous to balanced parentheses):

 "((()))" → "<<<>>>"
 "(()())" → "<<><>>"
 "(())()" → "<<>><>"
 "()(())" → "<><<>>"
 "()()()" → "<><><>"
 Each sequence is generated by choosing to place '<' when remaining > 0, and '>' when there is at least one unmatched '<'.

 Input Format

 The first line contains a single integer, n, representing the total number of meetings.
 The next n lines each contain two space-separated integers, representing the start_time and end_time of a single meeting.
 6
 1 2
 3 4
 0 6
 5 7
 8 9
 5 9
 Explanation:

 n = 6, indicating there are six meetings to process.
 The subsequent six lines represent the start and end times for each meeting. For example, the first meeting starts at time 1 and ends at time 2.
 Constraints

 0 <= n <= 12
 n is an integer
 Output Format

 Return a STRING_ARRAY containing every valid sequence of 2·n characters where:

 Sample Input 0

 1
 Sample Output 0

 <>
 Sample Input 1

 2
 Sample Output 1

 <<>>
 <><>
 
 link: https://www.hackerrank.com/contests/software-engineer-prep-kit/challenges/generate-valid-angle-bracket-sequences
 */


struct ExPR13 {
    func solution(input: InputProvider = DefaultInputProvider()) -> [String] {
        guard let nInput = input.readLine(), let n = Int(nInput)
        else { return [] }

        return generateAngleBracketSequences(n: n)
    }
}


/*
 Não soube fazer. Vi q iria demorar muito.
 PS: não foi enviado
 */
fileprivate func generateAngleBracketSequences(n: Int) -> [String] {
    aiSolution(n: n)
}


/*
 Backtracking para gerar todas as sequencias validas de n pares de '<' e '>'.

 A ideia central:
 - Rastreia quantos '<' (open) e '>' (close) ja foram colocados
 - A cada passo, tenta adicionar '<' ou '>'
 - Adiciona '<' se ainda nao colocou todos os n pares de abertura (open < n)
 - Adiciona '>' somente se ha um '<' sem par correspondente (close < open)
 - Quando a string tem n*2 caracteres, esta completa e e adicionada ao resultado

 Exemplo para n=2:
 backtrack("", 0, 0)
   → add '<': backtrack("<", 1, 0)
       → add '<': backtrack("<<", 2, 0)
           → nao pode add '<' (open == n)
           → add '>': backtrack("<<>", 2, 1)
               → add '>': backtrack("<<>>", 2, 2) ✓ completo
       → add '>': backtrack("<>", 1, 1)
           → add '<': backtrack("<><", 2, 1)
               → add '>': backtrack("<><>", 2, 2) ✓ completo
           → nao pode add '>' (close == open)

 Resultado: ["<<>>", "<><>"]
 */
fileprivate func aiSolution(n: Int) -> [String] {
    guard n > 0 else { return [] }

    var result = [String]()

    func backtrack(current: String, open: Int, close: Int) {
        // Sequencia completa
        if current.count == n * 2 {
            result.append(current)
            return
        }

        // Ainda pode abrir '<'
        if open < n {
            backtrack(current: current + "<", open: open + 1, close: close)
        }

        // Pode fechar '>' quando ha '<' sem par
        if close < open {
            backtrack(current: current + ">", open: open, close: close + 1)
        }
    }

    backtrack(current: "", open: 0, close: 0)
    return result
}
